[[project]]
name = "demo1.1"
alias = "d1.1"
description = "Demo 1.1"

[[project.item]]
name = "demo1.1.1"
alias = "d1.1.1"
path = "/demo1.1.1-path"


[[project.item]]
name = "demo1.1.2"
alias = "d1.1.2"
path = "/demo1.1.2-path"